# Site settings
title: Paleta
description: > #
  A set of style guides for several Upper Canada College associated organistations.
baseurl: "/paleta"
url: "https://malsf21.github.io"

# Social Settings
twitter: malsf21
github:  malsf21
email: matthew.wang@ucc.on.ca
website: "https://matthewwang.me"
repo: "https://github.com/malsf21/paleta/"

# Build settings
markdown: kramdown

collections:
  wac:
    output: true
    layout: wac
