# Site settings
title: UCC Clubs Style Guides
description: > # this means to ignore newlines until "baseurl:"
  Style guides for WAC, OMUN, Convergence, and a plethora of other things.
baseurl: "/paleta"
url: "https://malsf21.github.com"

# Social Settings
twitter: malsf21
github:  malsf21
email: matthew.wang@ucc.on.ca
website: "https://matthewwang.me"
repo: "https://malsf21.github.com/style/"

# Build settings
markdown: kramdown

collections:
  wac:
    output: true
    layout: wac
